#!/usr/bin/env ruby

git_bundles = [ 
  # "git://github.com/ervandew/supertab.git",
  # "https://github.com/Lokaltog/powerline.git",
  # "https://github.com/bling/vim-airline.git",
  "git://github.com/vim-scripts/AutoClose.git",
  "https://github.com/chriskempson/vim-tomorrow-theme.git",
  # "https://github.com/wincent/Command-T.git",
  "https://github.com/kien/ctrlp.vim.git",
  "https://github.com/tpope/vim-abolish.git",
  "https://github.com/mileszs/ack.vim.git",
  "https://github.com/kien/rainbow_parentheses.vim.git",
  "git://github.com/godlygeek/tabular.git",
  "git://github.com/msanders/snipmate.vim.git",
  "git://github.com/pangloss/vim-javascript.git",
  "git://github.com/scrooloose/nerdtree.git",
  "git://github.com/timcharper/textile.vim.git",
  "git://github.com/tpope/vim-bundler.git",
  # "git://github.com/tpope/vim-cucumber.git",
  "git://github.com/tpope/vim-endwise.git",
  "git://github.com/tpope/vim-fugitive.git",
  "git://github.com/tpope/vim-git.git",
  "git://github.com/tpope/vim-haml.git",
  "git://github.com/tpope/vim-markdown.git",
  "git://github.com/tpope/vim-rails.git",
  "git://github.com/tpope/vim-repeat.git",
  "git://github.com/tpope/vim-surround.git",
  # "git://github.com/tpope/vim-vividchalk.git",
  "git://github.com/altercation/vim-colors-solarized.git",
  # "https://github.com/morhetz/gruvbox.git",
  # "https://github.com/tomasr/molokai.git",
  "git://github.com/tsaleh/vim-matchit.git",
  # "git://github.com/tpope/vim-commentary.git",
  "https://github.com/tomtom/tcomment_vim.git",
  "git://github.com/vim-ruby/vim-ruby.git",
  "https://github.com/lucapette/vim-ruby-doc.git",
  "https://github.com/kchmck/vim-coffee-script.git",
  "https://github.com/rizzatti/dash.vim.git", #plugin do Dash.app
  "git://github.com/nathanaelkane/vim-indent-guides.git"
  # "git://github.com/tsaleh/vim-shoulda.git",
  # "git://github.com/tsaleh/vim-tmux.git",
  # "git://github.com/vim-scripts/Gist.vim.git",
  # "git://github.com/vim-scripts/TailMinusF.git",
]

vim_org_scripts = [
  ["IndexedSearch", "7062",  "plugin"],
  ["jquery",        "12107", "syntax"],
  ["TagList",       "7701",  "zip"],
]

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

FileUtils.cd(bundles_dir)

puts "trashing everything (lookout!)"
Dir["*"].each {|d| FileUtils.rm_rf d }

git_bundles.each do |url|
  dir = url.split('/').last.sub(/\.git$/, '')
  puts "unpacking #{url} into #{dir}"
  `git clone #{url} #{dir}`
  # FileUtils.rm_rf(File.join(dir, ".git"))
end

vim_org_scripts.each do |name, script_id, script_type|
  puts "downloading #{name}"
  if script_type == 'zip'
    local_file = File.join(name, "#{name}.#{script_type}")
  else
    local_file = File.join(name, script_type, "#{name}.vim")
  end
  FileUtils.mkdir_p(File.dirname(local_file))
  File.open(local_file, "w") do |file|
  file << open("http://www.vim.org/scripts/download_script.php?src_id=#{script_id}").read
end

if script_type == 'zip'
  `unzip #{local_file} -d #{name}`
  FileUtils.rm_rf(local_file)
end
end

